# Generated by Django 5.0.3 on 2024-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giganti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('immagine', models.ImageField(upload_to='')),
                ('prezzo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('immagine', models.ImageField(upload_to='')),
                ('prezzo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('immagine', models.ImageField(upload_to='')),
                ('prezzo', models.FloatField()),
            ],
        ),
    ]
