# Generated by Django 5.0.3 on 2024-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0002_schnauzer_delete_giganti_delete_nani_delete_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='schnauzer',
            name='sesso',
            field=models.CharField(blank=True, choices=[('maschio', 'Maschio'), ('femmina', 'Femmina')], max_length=10, null=True),
        ),
    ]
