# Generated by Django 5.0.3 on 2024-03-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0003_schnauzer_sesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='schnauzer',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
