# Generated by Django 5.0.3 on 2024-05-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0007_prenotazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='cane',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='numero_ospiti',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
