# Generated by Django 5.0.3 on 2024-07-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0008_remove_prenotazione_cane_prenotazione_numero_ospiti'),
    ]

    operations = [
        migrations.AddField(
            model_name='schnauzer',
            name='prenotato',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Prenotazione',
        ),
    ]
