# Generated by Django 5.0.3 on 2024-07-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0009_schnauzer_prenotato_delete_prenotazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schnauzer',
            name='prenotato',
        ),
    ]
