# Generated by Django 5.0.3 on 2024-07-30 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0010_remove_schnauzer_prenotato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schnauzer',
            name='prenotato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schnauzer',
            name='utente_prenotazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
