# Generated by Django 5.0.3 on 2024-10-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0011_schnauzer_prenotato_schnauzer_utente_prenotazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addestramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('agility', 'Agility'), ('obedience', 'Obedience')], max_length=15)),
                ('descrizione', models.TextField()),
                ('immagine', models.ImageField(default='path/to/default/image.jpg', upload_to='')),
                ('durata', models.PositiveIntegerField(default=60)),
                ('prezzo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='schnauzer',
            name='prenotato',
        ),
        migrations.RemoveField(
            model_name='schnauzer',
            name='utente_prenotazione',
        ),
    ]
