# Generated by Django 5.0.3 on 2024-10-28 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0012_addestramento_remove_schnauzer_prenotato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lezione', models.DateField()),
                ('orario_lezione', models.TimeField()),
                ('taglia_cane', models.CharField(choices=[('nano', 'Cucciolo Nano'), ('standard', 'Cucciolo Standard'), ('gigante', 'Cucciolo Gigante')], max_length=10)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='Geo.addestramento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
