# Generated by Django 5.1.3 on 2024-11-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0017_alter_prenotazione_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
