# Generated by Django 5.1.3 on 2024-11-27 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0018_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifica',
            name='letto',
        ),
        migrations.AddField(
            model_name='notifica',
            name='prenotazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Geo.prenotazione'),
        ),
    ]
