# Generated by Django 5.1.3 on 2024-11-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0019_remove_notifica_letto_notifica_prenotazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifica',
            name='user',
        ),
    ]
