# Generated by Django 5.1.3 on 2024-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0025_alter_notifica_prenotazione_alter_notifica_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifica',
            name='user',
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='cognome',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='nome',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='taglia',
            field=models.CharField(choices=[('grande', 'Grande'), ('media', 'Media'), ('piccola', 'Piccola')], default='media', max_length=10),
        ),
    ]
