# Generated by Django 5.1.3 on 2024-11-28 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0027_delete_notifica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.CharField(max_length=500)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('prenotazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.prenotazione')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
