# Generated by Django 5.1.3 on 2024-11-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0028_notifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='is_annullata',
            field=models.BooleanField(default=False),
        ),
    ]
