# Generated by Django 5.1.3 on 2024-12-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0032_alter_notifica_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='is_annullata',
        ),
    ]
