# Generated by Django 5.1.3 on 2024-12-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0033_remove_prenotazione_is_annullata'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('attiva', 'Attiva'), ('annullata', 'Annullata')], default='attiva', max_length=10),
        ),
    ]
